### ISSUE TITLE
availability of exposing DbSetMock or updating the list

### ISSUE THREAD

**Issue by haruair** [MichalJankowskii/Moq.EntityFrameworkCore#1]
The package saves more lines from my codes. Thanks for the work! After mocking the context, I want to check the dbSet if a new item added in the list.

```csharp
// ...
var user = userService.AddUser("koalalover", "John Kangaroo");
mockDbSet.Verify(m => (It.IsAny<User>()), Times.Once());
```

Currently, the list is not referenced via context, so the test below is failed.

```csharp
var users = new List<User>();
var mockContext = new Mock<SomeContext>();
mockContext.Setup(m => m.Users).Returns(users);

var postService = new PostService(mockContext.Object);
var user = userService.AddUser("koalalover", "John Kangaroo");

Assert.Equal(1, users.Count); // Actual: 0
```

If DbSet is able to expose outside, I can test this scenario even the code will verbose. Is there any capability for this case? Please let me know.

**Comment by MichalJankowskii** [comment]
I didn't notice your issue. I will try to check it tomorrow.

**Comment by MichalJankowskii** [comment]
Please find a short explanation why this library is not supporting such scenario.
With this library you can simulate your repository in case of retrieving information. In your case you would like to build a simulator of EntityFramework. In your test case you would like to check if the element has been added to DbSet by checking the collection. Moreover, from my perspective this is not the correct way of doing that because you are basing your unit test on implementation. Moreover, in your test you should only verify if add method has been executed.
Here is an example of such test:
```csharp            
// Arrange
var user = Fixture.Build<User>().Create();
var usersDb = new Mock<DbSet<User>>();
var usersContextMock = new Mock<UsersContext>();
usersContextMock.Setup(x => x.Users).Returns(usersDb.Object);
var usersService = new UsersService(usersContextMock.Object);

// Act
usersService.AddUser(user);

// Assert
usersDb.Verify(x => x.Add(It.Is<User>(y => y == user)), Times.Once);
usersContextMock.Verify(x => x.SaveChanges(), Times.Once);
```
