### ISSUE TITLE
Filtering collections does not appear to work

### ISSUE THREAD

**Issue by dzeidman** [MichalJankowskii/Moq.EntityFrameworkCore#30]
My class looks like this:

 ```
public class Transformation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TransformationId { get; set; }
        public string Name { get; set; } = "";
        public string Description { get; set; } = "";
        public virtual ICollection<TransformationEntry> TransformationEntries { get; set; } = new List<TransformationEntry>();
   }
```
When I use the following with the mock:

`var transformation = await Context.Transformations.Include(f => f.TransformationEntries.Take(2));`

It brings over all entries. The Take(2) appears to be ignored. When I run this on a real data set it only returns two items.

**Comment by MichalJankowskii** [comment]
Hi,

It is because you are mocking `Context.Transformations` and when you are executing `Include` it is actually mocked method that is being ignored. 

You need to extent your mock setup and add there also configuration for `Include` method.

**Comment by dzeidman** [comment]
Struggling to implement that so any help you (or anybody else) can offer is appreciated...

**Comment by MichalJankowskii** [comment]
It is not obvious. `Include` is an extension method and `Moq` does not support having an extension method in `Setup`.

If you want to mock it you can create a wrapper for `Include` that can be easily mocked.

I do not like this approach because it is complicating code finally and add unclear abstractions. I would instead mocking `Include` return object with two items and assume that EF is working correctly.
