### ISSUE TITLE
New feature from .net core 7 not mocked.

### ISSUE THREAD

**Issue by AndreyKrivcov** [MichalJankowskii/Moq.EntityFrameworkCore#31]
Hello, can you please add (or suggest how to mock) such extension methods like "ExrcuteUpdateAsync" that are come from ,net core 7 updates in EF ?

More details is in video presentation from dotnet: https://youtu.be/rrKhbiXydKs?t=1232

When I tried to use this features, my unit tests are crashed...

**Comment by maik-hasler** [comment]
The `ExecuteUpdateAsync` extension method introduced in .NET Core 7 for Entity Framework (EF) is designed for immediate execution against the database, bypassing the EF change tracker. 
With that beeing said, this method cannot be directly used with a mocked DbContext because it interacts directly with the database and doesn't utilize the EF change tracker. Mocked contexts simulate database interactions but don't actually execute queries on a real database.

If you're facing issues with unit tests crashing when using this method, you should consider:
1. **Separate Integration Tests:** Instead of using the mocked DbContext for these tests, create separate integration tests that run against a real database. This way, you can test the actual behavior of `ExecuteUpdateAsync`.
2. **Limit Mocked Tests**: Focus your unit tests on logic that doesn't involve direct database interaction. For operations involving `ExecuteUpdateAsync`, rely more on integration tests to validate the database interactions.

Remember, unit tests are primarily for testing isolated units of code, while integration tests cover interactions between different components, which includes database interactions.

I hope I could help you.
