### ISSUE TITLE
Add support for mocking ExecuteUpdate am ExecuteDelete

### ISSUE THREAD

**Issue by Roel1l** [MichalJankowskii/Moq.EntityFrameworkCore#38]
Would it be possible to add support for mocking or being able to execute these EF core functions:

https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete

Currently I am getting the following error:

System.InvalidOperationException : There is no method 'ExecuteUpdate' on type 'Microsoft.EntityFrameworkCore.RelationalQueryableExtensions' that matches the specified arguments

Even though the function does work when running the code not through unit tests

**Comment by MichalJankowskii** [comment]
Hi @Roel1l,

It is not possible to mock every function of EF core in the lib. Going with this approach would mean that probably the lib would need to simulate SQL db in most of features.

Because some of the elements need to be tested in env having real db.

Pls check here: [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/)
